Feat/rl 7000615707/add video to oam
blackberggroup/VA-OAM pull request #13
Opened 2024-07-10 21:11 UTC by RyanCrux

## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

Added video to homepage AND to news & events

## Related Tickets & Documents
- Monday Task: https://blackberg-group.monday.com/boards/1931719392/pulses/7000615707

## QA Instructions, Screenshots, Recordings

review sandbox version, compared to mockup files in Monday task.

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

2024-07-10 21:17 UTC, RyanCrux commented
Link to homepage: https://www.dev-innovation.bgsandbox.com/oam/

Link to News & Events: https://www.dev-innovation.bgsandbox.com/oam/news-and-events/

2024-07-11 17:00 UTC, ecstech-admin requested changes
Looks great!

Add space between videos on home page in mobile view
![image](https://github.com/blackberggroup/VA-OAM/assets/119957662/9f60ea90-1706-44df-a14e-03604246705d)

2024-07-11 21:06 UTC, RyanCrux commented
Good catch - all set here: 
<img width="549" alt="Screenshot 2024-07-11 at 5 02 27 PM" src="https://github.com/blackberggroup/VA-OAM/assets/153299181/9559d464-f3bb-4a07-94b1-88f505da6f30">

2024-07-11 21:29 UTC, ecstech-admin requested changes
Looks good at mobile-lg but still getting spacing issue at mobile breakpoint. Try changing "mobile-lg:margin-bottom-10" to "mobile:margin-bottom-10".

2024-07-11 21:29 UTC, ecstech-admin commented on _site/index.html
Looks good at mobile-lg breakpoint but still getting spacing issue at mobile breakpoint.

Try changing "mobile-lg:margin-bottom-10" to "mobile:margin-bottom-10".

2024-07-12 12:19 UTC, will-bbg approved these changes

2024-07-12 12:52 UTC, merged